name: practica3_flutter
description: Aplicación de cámara y micrófono - Práctica 3 ESCOM IPN
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gestor de estado
  provider: ^6.1.2

  # Cámara
  camera: ^0.10.5+9

  # Micrófono y audio
  audioplayers: ^6.0.0
  flutter_sound: ^9.2.13

  # Almacenamiento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Permisos
  permission_handler: ^11.3.1

  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
